### ISSUE TITLE
Mysterious FileNotFoundError on some task tabs in some annotation repo branches

### ISSUE THREAD

**Issue by marcverhagen** [clamsproject/internal-anno-eval-dashboard#1]
### Bug Description

The dashboard gives an error when selecting some tabs in some branches. This happens when reading data for a task that includes sub directories in the golds directory.

### Reproduction steps

Start the dashboard  with `streamlit run app.py`.

Then select "Annotation Viewer" > "Tasks" > "scene-recognition" > "Gold files". This is all good.

Then select the "85-timeframes" branch. You get the error:

```
Traceback (most recent call last):
  File "/Applications/ADDED/venv/clams/dashboard/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/Users/marc/Documents/git/clams/dashboard/code/app.py", line 105, in <module>
    annotation_viewer(ANNOTATIONS, CHECKOUT)
  File "/Users/marc/Documents/git/clams/dashboard/code/viewers/annotation_viewer.py", line 56, in viewer
    gold_tab2.text(task_obj.gold_content(selected_gold))
  File "/Users/marc/Documents/git/clams/dashboard/code/annotation.py", line 178, in gold_content
    with open(gold_path) as fh:
FileNotFoundError: [Errno 2] No such file or directory: '../../aapb-annotations/scene-recognition/golds/cpb-aacip-08fb0e1f287.csv'
```

If instead of "Gold files" one of the tabs to the right was selected ("Data drops", "Batches" or "Process.py") you get the same error. No error if you select "Readme" or "Gold directory".

Oddly, if you start the dashboard with `streamlit run app.py -- debug` then there is no problem.

**Comment by marcverhagen** [comment]
Fixed while working on https://github.com/clamsproject/internal-anno-eval-dashboard/commit/737dc04f7e63bcdde9af190f66e794f3dba88b7c. It is unclear why adding the debug made a difference.
